In [1]:
import pandas as pd
import numpy as np
from path import Path

In [8]:
file_path = Path("../../data/zillow_data/City_Zhvi_SingleFamilyResidence.csv")

zillow_df = pd.read_csv(file_path)

zillow_df.head()

,Unnamed: 0,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,1996-01-31,...,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31
0,0,6181,0,New York,City,NY,NY,New York-Newark-Jersey City,Queens County,208545.0,...,672433.0,671924.0,671423.0,670719.0,669974.0,669118.0,668736.0,668740.0,668581.0,668030.0
1,1,12447,1,Los Angeles,City,CA,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,192855.0,...,745290.0,746729.0,748924.0,751756.0,755716.0,759279.0,764877.0,770853.0,779717.0,788751.0
2,2,39051,2,Houston,City,TX,TX,Houston-The Woodlands-Sugar Land,Harris County,95018.0,...,189803.0,190437.0,191052.0,191483.0,192124.0,192620.0,193202.0,193427.0,193991.0,194986.0
3,3,17426,3,Chicago,City,IL,IL,Chicago-Naperville-Elgin,Cook County,126867.0,...,226322.0,226635.0,226796.0,226645.0,226505.0,226430.0,226454.0,226727.0,227077.0,227605.0
4,4,6915,4,San Antonio,City,TX,TX,San Antonio-New Braunfels,Bexar County,94406.0,...,183622.0,184246.0,184831.0,185752.0,186401.0,187159.0,187339.0,187886.0,188055.0,188650.0

In [81]:
state = ["FL", "CA"]

State_data = zillow_df[zillow_df.State.isin(state)]



State_data.head()

,Unnamed: 0,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,1996-01-31,...,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31
1,1,12447,1,Los Angeles,City,CA,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,192855.0,...,745290.0,746729.0,748924.0,751756.0,755716.0,759279.0,764877.0,770853.0,779717.0,788751.0
8,8,54296,8,San Diego,City,CA,CA,San Diego-Carlsbad,San Diego County,214715.0,...,709024.0,711846.0,714119.0,716734.0,718446.0,722025.0,726601.0,733084.0,738722.0,745231.0
11,11,33839,11,San Jose,City,CA,CA,San Jose-Sunnyvale-Santa Clara,Santa Clara County,232040.0,...,1085372.0,1076216.0,1074787.0,1079039.0,1083387.0,1088611.0,1097565.0,1113006.0,1128436.0,1145150.0
12,12,25290,12,Jacksonville,City,FL,FL,Jacksonville,Duval County,85992.0,...,191089.0,191476.0,192127.0,192753.0,193752.0,194465.0,195560.0,197045.0,199119.0,201483.0
14,14,20330,14,San Francisco,City,CA,CA,San Francisco-Oakland-Hayward,San Francisco County,299060.0,...,1463199.0,1464488.0,1462393.0,1467249.0,1473085.0,1482111.0,1495964.0,1504169.0,1512624.0,1515959.0

In [82]:
State_dropped=State_data.drop(columns=["Unnamed: 0", "RegionID", "SizeRank", "RegionType", "StateName"])

State_dropped.head()

,RegionName,State,Metro,CountyName,1996-01-31,1996-02-29,1996-03-31,1996-04-30,1996-05-31,1996-06-30,...,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31
1,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,192855.0,192899.0,192974.0,193133.0,193265.0,193453.0,...,745290.0,746729.0,748924.0,751756.0,755716.0,759279.0,764877.0,770853.0,779717.0,788751.0
8,San Diego,CA,San Diego-Carlsbad,San Diego County,214715.0,214359.0,214117.0,213632.0,213343.0,213140.0,...,709024.0,711846.0,714119.0,716734.0,718446.0,722025.0,726601.0,733084.0,738722.0,745231.0
11,San Jose,CA,San Jose-Sunnyvale-Santa Clara,Santa Clara County,232040.0,231403.0,231196.0,230868.0,230976.0,231234.0,...,1085372.0,1076216.0,1074787.0,1079039.0,1083387.0,1088611.0,1097565.0,1113006.0,1128436.0,1145150.0
12,Jacksonville,FL,Jacksonville,Duval County,85992.0,86107.0,86225.0,86436.0,86621.0,86815.0,...,191089.0,191476.0,192127.0,192753.0,193752.0,194465.0,195560.0,197045.0,199119.0,201483.0
14,San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,299060.0,298066.0,297387.0,296175.0,295267.0,294811.0,...,1463199.0,1464488.0,1462393.0,1467249.0,1473085.0,1482111.0,1495964.0,1504169.0,1512624.0,1515959.0

In [87]:
FL_CA_df = pd.melt(State_dropped, id_vars=["RegionName","State","Metro","CountyName"], 
                  var_name="Date", value_name="Avg_Price")

In [88]:
FL_CA_df.set_index("RegionName")

,State,Metro,CountyName,Date,Avg_Price
RegionName,,,,,
Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,1996-01-31,192855.0
San Diego,CA,San Diego-Carlsbad,San Diego County,1996-01-31,214715.0
San Jose,CA,San Jose-Sunnyvale-Santa Clara,Santa Clara County,1996-01-31,232040.0
Jacksonville,FL,Jacksonville,Duval County,1996-01-31,85992.0
San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,1996-01-31,299060.0
...,...,...,...,...,...
Goodland,FL,Naples-Immokalee-Marco Island,Collier County,2020-03-31,252414.0
McIntosh,FL,Ocala,Marion County,2020-03-31,206490.0
Camp Meeker,CA,Santa Rosa,Sonoma County,2020-03-31,396362.0
Bear Valley,CA,NaN,Alpine County,2020-03-31,448221.0
North Palm Springs,CA,Riverside-San Bernardino-Ontario,Riverside County,2020-03-31,260092.0

In [89]:
#Export
file_path_export=Path("../../data/raw/Housing_cleaned.csv")
FL_CA_df.to_csv(file_path_export)